# -*- coding: utf-8 -*-
"""Code_For_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eS3POS9Hi8mq8oEly9zZdCZLbgVyP9VK
"""

import os
import matplotlib.pyplot as plt
from PIL import Image

# Function to visualize images
def visualize_images(file_list, base_path):
    for image_file in file_list:
        if image_file.endswith(('.jpg', '.png')):
            img_path = os.path.join(base_path, image_file)
            img = Image.open(img_path)
            plt.figure(figsize=(8, 8))
            plt.imshow(img)
            plt.title(image_file)
            plt.axis('off')
            plt.show()

# File list and base path
file_list = [
    "val_batch0_labels.jpg",
    "val_batch0_pred.jpg",
    "val_batch1_labels.jpg",
    "val_batch1_pred.jpg",
    "val_batch2_labels.jpg",
    "val_batch2_pred.jpg",
    "confusion_matrix.png",
]
base_path = '/content/drive/MyDrive/Dataset/result'

# Visualize images
visualize_images(file_list, base_path)