# -*- coding: utf-8 -*-
"""Data_Preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZbFGn32eBkU9wQt0O_BD1zOunp_VuTt
"""

import os
 import random
 import shutil
 from sklearn.model_selection import train_test_split

 def create_splits(annotations_dir, images_dir, train_ratio, val_ratio, test_ratio):
   """
   Creates train, validation, and test splits for YOLOv9.

   Args:
     annotations_dir: Path to the directory containing annotation files (.txt format).
     images_dir: Path to the directory containing corresponding images (.jpg format).
     train_ratio: Ratio of data for training.
     val_ratio: Ratio of data for validation.
     test_ratio: Ratio of data for testing.
   """

   assert train_ratio + val_ratio + test_ratio == 1.0, "Ratios must sum to 1.0"

   annotations = [f for f in os.listdir(annotations_dir) if f.endswith('.txt')]
   random.shuffle(annotations)

   train_split = int(len(annotations) * train_ratio)
   val_split = int(len(annotations) * val_ratio)

   train_annotations = annotations[:train_split]
   val_annotations = annotations[train_split:train_split + val_split]
   test_annotations = annotations[train_split + val_split:]

   splits = {
       'train': train_annotations,
       'val': val_annotations,
       'test': test_annotations
   }

   # Create YOLOv9 data.yaml file content
   yaml_content = f"""
   train: {images_dir}/train/images
   val: {images_dir}/val/images
   test: {images_dir}/test/images
   nc:4
   """

   with open('data.yaml', 'w') as f:
       f.write(yaml_content)

   for split_name, split_annotations in splits.items():
       # Create directories for images and labels
       os.makedirs(os.path.join(images_dir, split_name, 'images'), exist_ok=True)
       os.makedirs(os.path.join(images_dir, split_name, 'labels'), exist_ok=True)

       for annotation in split_annotations:
           image_name = annotation.replace('.txt', '.jpg')
           image_src_path = os.path.join(images_dir, image_name)
           image_dst_path = os.path.join(images_dir, split_name, 'images', image_name)
           shutil.copy(image_src_path, image_dst_path)

           label_src_path = os.path.join(annotations_dir, annotation)
           label_dst_path = os.path.join(images_dir, split_name, 'labels', annotation)
           shutil.copy(label_src_path, label_dst_path)

 def create_image_folders(annotations_dir, images_dir):
   """
   This function is not required for YOLOv9.
   """
   pass

 if _name_ == "_main_":
   annotations_dir = '/content/Annotations'
   images_dir = '/content/images'
   train_ratio = 0.7
   val_ratio = 0.2
   test_ratio = 0.1
   create_splits(annotations_dir, images_dir, train_ratio, val_ratio, test_ratio)